hw11- сделала Page factory для классов CartPage,CheckoutOverviewPage,…
MashaChornaya/SauceDemo pull request #3
Opened 2022-07-19 21:44 UTC by MashaChornaya

…ItemDetailsPage.Ожидания в loginPositiveTest(прошел),ожидания в burgerMenuTest и finishActionOnCheckoutOverviewPageTest (с ожиданиями все ок, но падает тест по NullPointerException: Cannot invoke "Pages.HomePage.isBurgerMenuAllItemsDisplayed()" because "this.homePage" is null)Вопрос,это из-за чего это может быть?

2022-07-20 08:43 UTC, voropa requested changes

2022-07-20 08:43 UTC, voropa commented on src/test/java/Pages/CartPage.java
Вы забыли добавить PageFactory.initiElements() в конструктор, оно не будет работать...

2022-07-20 08:43 UTC, voropa commented on src/test/java/Pages/CheckoutOverviewPage.java
>          super(driver);
То же самое тут

2022-07-20 08:43 UTC, voropa commented on src/test/java/Pages/ProductsPage.java
> +    public void clickAddToCardButton() {
Так а какой товар добавляется в корзину таким методом? Первый попавшийся?
мы же специально добавляли логику с динамическим локатором и передавали название товара во все методы, чтобы работать с конкретным товаром по  его имени

2022-07-20 08:43 UTC, voropa commented on src/test/java/Tests/CheckoutTest.java
> +        WebElement ponyPicture = (new WebDriverWait(driver, 5))
В тестовых методах не должно быть никаких техническим методов и работы с драйвером или ожиданиями. Вынесите это ожидание в отдельный метод в классе страницы и вызывайте его тут

2022-07-20 08:43 UTC, voropa commented on src/test/java/Tests/ItemDetailsTest.java
> +           WebElement burgerMenu = (new WebDriverWait(driver, 5))
А зачем вообще тут это ожидание?

2022-07-20 08:43 UTC, voropa commented on src/test/java/Tests/ItemDetailsTest.java
> +           WebElement burgerMenu = (new WebDriverWait(driver, 5))
Ожидания нужно вставлять там, где они действительно нужны, а тут от него гнет никакого смысла

2022-07-20 08:43 UTC, voropa commented on src/test/java/Tests/LoginTest.java
> +        WebElement productsPageEmblem = (new WebDriverWait(driver, 5))
То же самое

2022-07-20 08:46 UTC, voropa commented
> …ItemDetailsPage.Ожидания в loginPositiveTest(прошел),ожидания в burgerMenuTest и finishActionOnCheckoutOverviewPageTest (с ожиданиями все ок, но падает тест по NullPointerException: Cannot invoke "Pages.HomePage.isBurgerMenuAllItemsDisplayed()" because "this.homePage" is null)Вопрос,это из-за чего это может быть?

потому что у вас обьект homePage не проинициализирован через new HomePage()
А вообще HomePage класс должен быть абстрактным, от которого мы наследуем другие страницы и мы не должны создавать обьект homePage и вызывать у него какие-то методы.
Нужно работать с другими обльектами страниц. 
Например, если вы находитесь на странице ProductsPag, то у нее нужно вызват ьметод isBurgerMenuAllItemsDisplayed

2022-07-21 17:24 UTC, MashaChornaya commented
Так у меня же Home Page class абстрактный, и я не вызываю нигде методы от homePage.("Например, если вы находитесь на странице ProductsPag, то у нее нужно вызват ьметод isBurgerMenuAllItemsDisplayed"-я же так и делала)Или вы про то, что  в base Page нельзя писать методы?

2022-07-21 20:42 UTC, voropa requested changes

2022-07-21 20:42 UTC, voropa commented on src/test/java/Pages/ProductsPage.java
> +    public void addToCardButton(String productsName) {
я не монимаю что делают эти методы. Вчитайтесь внимательно в их названия и в то, какие действия они выполняют - явно найдете расхождения

2022-07-21 20:42 UTC, voropa commented on src/test/java/Pages/ProductsPage.java
> +    public void addToCardButton(String productsName) {
Строки 47-56

2022-07-21 20:42 UTC, voropa commented on src/test/java/Tests/CheckoutTest.java
> +   WebElement ponyPicture= (WebElement) new WebDriverWait(driver,10).until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".pony_express")));
Это что за веб элемент посреди тестовых методов?

2022-07-21 20:42 UTC, voropa commented on src/test/java/Tests/CheckoutTest.java
> +   WebElement ponyPicture= (WebElement) new WebDriverWait(driver,10).until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".pony_express")));
У вас из-за этого не запускаются checkoutTests

2022-07-21 20:42 UTC, voropa commented on src/test/java/Tests/ItemDetailsTest.java
>          Assert.assertEquals(itemDetailsPage.getItemDescription(), "It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day out
Тут падает с nosuchElementException, потому что вы находитесь на стронице itemDetails,а вызываете метод addToCartButton() со странице productsPage, естественно такого элемента нет на странице

2022-07-24 21:39 UTC, voropa requested changes

2022-07-24 21:39 UTC, voropa commented on src/test/java/Pages/FinishPage.java
> +    public boolean waitPonyPicture(){
Методы ожидания должны быть типа void. они ничег оне возвращают, а просто ждут и если не дожидаются условия, то выдвют exception, а у вас метод всегда возвращает true

2022-07-26 19:37 UTC, voropa requested changes

2022-07-26 19:37 UTC, voropa commented on src/test/java/Pages/FinishPage.java
> +    public void waitPonyPicture(){
Так он у вас действительно нигде не вызывается по коду, вот и пишет вам идея, что метод не используется

2022-07-26 20:08 UTC, MashaChornaya commented on src/test/java/Pages/FinishPage.java
> +    public void waitPonyPicture(){
я просто не понимаю как должна тогда выглядеть проверка на ожидание картинки?  на такую проверку -Assert.assertTrue(finishPage.waitPonyPicture()) ругается из-за типа воид, если  Assert.assertEquals то в expected как я поняла надо писать finishPage.isPonyPictureDisplayed(), а что писать в actual,я не поняла

2022-07-27 08:45 UTC, voropa commented on src/test/java/Pages/FinishPage.java
> +    public void waitPonyPicture(){
"проверка на ожидание картинки" -странная формулировка
проверка и ожидание - это 2 разных действия, которые должны быть реализованы двумя разными методами. 
Если нужно подождать появление - вызываете метод ожидания, если нужно проверить наличие - вызываете метод для проверки

2022-07-27 15:15 UTC, MashaChornaya commented on src/test/java/Pages/FinishPage.java
> +    public void waitPonyPicture(){
спасибо вам за объяснение)

2022-07-27 21:04 UTC, voropa approved these changes

2022-07-28 17:43 UTC, merged