До конца исправила логирование
MashaChornaya/SauceDemo pull request #6
Opened 2022-08-20 13:32 UTC by MashaChornaya

2022-08-21 19:07 UTC, voropa requested changes

2022-08-21 19:07 UTC, voropa commented on Jenkinsfile
> +         stage('Browser') {
Это что?)
Такой код будет просто выводить в консоль "chrome", "firefox"

2022-08-21 19:07 UTC, voropa commented on Jenkinsfile
> +     gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'SUITE NAME', type: 'PT_BRANCH'
Вероятно, SUITE NAME должен быть параметром другого типа, это же не branch и он не имеет отношения в git, а он у вас параметр типа gitParameter

2022-08-27 12:17 UTC, voropa requested changes

2022-08-27 12:17 UTC, voropa commented on Jenkinsfile
> -pipeline {
Почему вы его удалили?

2022-08-27 12:17 UTC, voropa commented on src/test/java/Pages/LoginPage.java
> +        log.info("Set username 'standard_user' from Base test");
Логирование динамических атрибутов нужно делать след. образом:
"Set username '{userName}' from Base test",
где {userName} - это входной аргумент вашего метода, тогда при выполнении теста вместо {userName} в логе выведется реальное значение параметра, который передался в этот метод

2022-08-27 13:11 UTC, MashaChornaya commented on Jenkinsfile
> -pipeline {
завис интернет , а потом оказалось что два раза файл скинула, сейчас скину еще раз

2022-08-27 13:16 UTC, MashaChornaya commented on Jenkinsfile
> -pipeline {
не могу скинуть еще раз, сначала нужно замержить

2022-08-28 17:59 UTC, voropa requested changes

2022-08-28 17:59 UTC, voropa commented on src/test/java/Pages/CheckoutPage.java
> +        log.info("Set'{Tolstoy}' from Checkout Test");
Это все равно неправильно)
в {} вы должны писать имя переменной, которая используется как входной аргумент метода. У вас же не всегда будет lastName "Tolstoy", вы же можете любое значение туда передать

2022-09-04 10:48 UTC, voropa approved these changes

2022-09-04 11:05 UTC, merged